from summarise import summarise
import os
from openai import OpenAI


if __name__ == '__main__':
	example_summary = """This week's lecture covers gravitational forces, specifically Newton's law of universal gravitation. The force of gravity between two objects is directly proportional to the mass of each object and inversely proportional to the square of the distance between them. Mathematically, this is expressed as GF(m1, m2) = G(the gravitational constant)/(the distance between the objects)^(2/3). An object moving in a circle experiences a centripetal force equal to F(mv) = (mv)^(2)/r. This must equal the gravitational force exerted by the Sun on the Earth. Using this, one can calculate that the Sun's mass is 1.99 x 1030 kg.  There are also reminders that Lab 1 is due next week and there is a practice version available after the due date, and that Pre-reading 2 is due Sunday and the first quiz is Wednesday covering material through today, with no homework next week.
The Earth's velocity can be calculated using the formula c=2𝜋r, where c is the velocity, 𝜋 is the ratio of a circle's circumference to its diameter, and r is the radius of the orbit. Given that r=1.5×1011m for Earth's orbit around the Sun, the velocity is v=29,900 m/s. To calculate the Sun's mass, we can use the formula F=GMm/r^2, where F is the centripetal force, G is the gravitational constant, M is the mass of the Sun, m is the mass of the Earth, and r is the radius of the orbit. With the known values, we can calculate the mass of the Sun, which is 2×1030 kg. The Milky Way's mass can be calculated using the same formula, taking the velocity of stars at the edge of the Milky Way and their distance from the center into account.
There are 15 forms of energy, including potential energy, which can be stored, such as chemical energy stored in food or batteries. Gravitational potential energy, specifically, occurs when an object is at a height where gravity has the potential to cause it to accelerate. The formula for gravitational potential energy on the surface of the Earth is given by U = mgh, where m is the mass of an object, h is its height above the Earth's surface and g is the acceleration due to the Earth's gravity, 9.8 m/s2. Planets, moons and satellites also have kinetic and gravitational potential energy, which is conserved for bound orbits. If a ball is thrown with a speed slightly less or slightly more than the speed for a circular orbit, its orbit becomes an ellipse.
Geller et al.'s "Universe" provides an example on how to calculate the escape speed from a planet's surface. The formula for the escape speed is: 𝑣𝑣𝑐𝑐𝑑𝑑𝑐𝑐=2𝐺𝐺𝐺𝐺𝑟𝑟, where 𝑟𝑟 is the radius of the planet and 𝑐𝑐𝑑𝑑𝑑 is its mass. The book then asks what the Earth's radius would be, if the escape velocity from its surface was the speed of light. With the help of the given mass of the Earth, we can calculate the needed radius to be 9 mm. "Universe" also provides an exercise on how to calculate the distance between two objects in a binary system with the help of their masses and their radial velocity curves.
Astronomers have made a fascinating discovery, estimating that a black hole with a mass of around 68 solar masses is lurking around 8,000 light-years away from Earth. The finding came after they noticed a visible star accompanied by a unseen companion, which led them to estimate the mass of the invisible object based on the motion of the visible star. This estimate pointed towards a black hole, due to its large mass with very little light emission. The pair are estimated to be around 1.5 astronomical units apart. Additionally, an astronaut in the International Space Station feels weightless not because they are beyond the pull of gravity, but because they are in freefall around the Earth along with the station.
"""
